{% set name = "dftd3-python" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/simple-dftd3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5133b6f4835d595836a28d1c96974ccd713d7b238597d6f82da1f32a4a898afd

build:
  number: 0
  skip: true  # [win or (osx and (python_impl == 'cpython' and py<38))]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - python
    - cffi
    - pkg-config
  host:
    - python
    - pip
    - simple-dftd3
    - libblas
  run:
    - python
    - cffi
    - numpy
    - simple-dftd3


test:
  imports:
    - dftd3
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd3 -vv

about:
  home: https://github.com/awvwgk/simple-dftd3/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D3 project

extra:
  recipe-maintainers:
    - awvwgk
