{% set name = "dftd3-python" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd3/simple-dftd3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fde5e1bdac41c38692bfdb6abcad66fb9ccfe6e990a8d4cf54f44e7188d49b5a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}
    - cffi                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson                               # [build_platform != target_platform]
    - meson-python                        # [build_platform != target_platform]
    - pkg-config
    - python                              # [build_platform != target_platform]
    - python-build                        # [build_platform != target_platform]
  host:
    - cffi
    - libblas  # [unix]
    - meson
    - meson-python
    - pip
    - python
    - python-build
    - simple-dftd3 >={{ version }}
  run:
    - cffi
    - numpy
    - python


test:
  imports:
    - dftd3
    - dftd3.library
    - dftd3.interface
    - dftd3.parameters
    - dftd3.ase
    - dftd3.qcschema
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
    - tomli

about:
  home: https://github.com/awvwgk/simple-dftd3/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D3 project

extra:
  recipe-maintainers:
    - awvwgk
