{% set name = "dftd3-python" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd3/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 19400a176eb4dcee7b89181a5a5f0033fe6b05c52821e54896a98448761d003a

build:
  number: 0
  skip: true  # [osx and (python_impl == 'cpython' and py<38)]
  script:
    - set -ex  # [unix]
    - cd python
    - >
       meson setup _build
       ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
       --prefix=%PREFIX% --pkg-config-path=%LIBRARY_PREFIX%\lib\pkgconfig;%PREFIX%\lib\pkgconfig  # [win]
       --buildtype=release -Dpython_version={{ PYTHON }}
    - meson compile -C _build
    - meson install -C _build --no-rebuild
    - copy %SRC_DIR%\assets\parameters.toml %PREFIX%\lib\site-packages\dftd3  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - meson
    - python
    - pkg-config
  host:
    - python
    - cffi
    - pip
    - simple-dftd3 >={{ version }}
    - libblas  # [unix]
  run:
    - python
    - cffi
    - numpy


test:
  imports:
    - dftd3
    - dftd3.library
    - dftd3.interface
    - dftd3.parameters
    - dftd3.ase
    - dftd3.qcschema
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
    - tomli
  commands:
    - pytest --pyargs dftd3 -vv  # [build_platform == target_platform and py<=39]

about:
  home: https://github.com/awvwgk/simple-dftd3/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D3 project

extra:
  recipe-maintainers:
    - awvwgk
